from . import dish
from . import menu
from . import meal_register
from . import hr_employee
from . import data_master
from . import service
from . import register_employee
from . import confirm_dish
from . import order_dish
from . import popup
from . import product_product
from . import ir_sequence
from . import customer